# This question is asked by Google. You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’  ‘.
# Note: You may assume that at most one additional character can be added to t.

# Ex: Given the following strings...

# s = "foobar", t = "barfoot", return 't'
# s = "ide", t = "idea", return 'a'
# s = "coding", t "ingcod", return ''

def spot_difference(s:str, t: str):
    map = {}
    
    for i in s:
        if i in map:
            map[i] += 1
        else:
            map[i] = 1
    
    for j in t:
        if j in map:
            map[j] -= 1
        else:
            print(j)
            return
    
    for l in map.keys():
        if map[l] != 0:
            print(l)
            return
    
    print('')
    
    return

def spot_difference_alt(s:str, t:str):
    s_sorted = sorted(s)
    t_sorted = sorted(t)
    max_s_index = len(s_sorted) - 1
    
    for i in range(len(t_sorted)):
        if i > max_s_index:
            print(t_sorted[i])
            return
        
        if t_sorted[i] != s_sorted[i]:
            print(t_sorted[i])
            return
        pass
    
    print('')
    return
    

#tests
print("spotting the difference")
spot_difference("foobar", "barfoot")
spot_difference("ide", "idea")
spot_difference("coding", "ingcod")

print('\n-------------------------\n')
spot_difference_alt("foobar", "barfoot")
spot_difference_alt("ide", "idea")
spot_difference_alt("coding", "ingcod")